name: blog_client
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  injectable: ^2.5.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  auto_route: ^10.1.2
  get_it: ^8.2.0
  fpdart: ^1.1.1
  equatable: ^2.0.7
  image_picker: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  html_editor_enhanced: ^2.7.1
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  auto_route_generator: ^10.2.4
  injectable_generator: ^2.8.1
  freezed: ^3.2.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
